name: BuyCommand
main: net.mayateck.BuyCommand.BuyCommand
version: 0.01.00Alpha
website: 'https://github.com/Wehttam664/BuyCommand/wiki'
author: Wehttam664
depend: [Vault]
commands:
   buycommand:
      aliases: [bc, bcmd, buycmd]
      description: 'Command to buy a command.'
      permission: buycommand.buy
      permission-message: 'You cannot buy any commands. (Permissions)'
      usage: 'Un-handled Syntax Issue. Please report this to a developer.'
permissions:
   buycommand.*:
      description: 'Overall permission.'
      children:
         buycommand.buy: true
         buycommand.admin: false
   buycommand.buy:
      description: 'Permission to buy a command'

